
server {
    listen 80;
    server_name ojasio.com www.ojasio.com;
    root /path/to/dist;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    location ~ ^/blog/(.*)$ {
        try_files $uri $uri/ $uri.html /blog/$1/index.html /index.html;
    }

    error_page 404 /index.html;
}
